version: "3.7"
services:
  api_service:
    build: .
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/crud_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - 8080:8080
    depends_on:
      - postgres_db
  postgres_db:
    image: "postgres:11.4-alpine"
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: crud_db
      PGDATA: /var/lib/postgresql/data/pgdata